version: '3.8'

services:
  db:
    image: postgres:14
    container_name: betting-events-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bettingEventsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: ./betting-service
      dockerfile: Dockerfile
    container_name: betting-events-api
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/bettingEventsdb
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
